# Generated by Django 3.0.6 on 2020-05-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recolector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=25)),
                ('url_encontrado', models.URLField()),
                ('tienda', models.CharField(max_length=50)),
            ],
        ),
    ]
