# Generated by Django 3.0.6 on 2020-05-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recolector',
            old_name='url_encontrado',
            new_name='url_de_busqueda',
        ),
        migrations.RemoveField(
            model_name='recolector',
            name='tienda',
        ),
    ]
