# Generated by Django 3.0.6 on 2020-05-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0003_correo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recolector',
            new_name='Producto',
        ),
    ]
