# Generated by Django 3.0.6 on 2020-05-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0004_auto_20200527_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Existencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
